import Product from '#models/product'
import { BaseSeeder } from '@adonisjs/lucid/seeders'

export default class extends BaseSeeder {
  public async run() {
    await Product.createMany([
      { name: 'Torradeira Wi-Fi TurboToast', price: 150.0 },
      { name: 'Aspirador de Migalhas Vortex', price: 250.0 },
      { name: 'Mouse Ergonômico Pata de Gato', price: 120.0 },
      { name: 'Teclado Anti-Gato ClickBlock', price: 300.0 },
      { name: 'Monitor Anti-Sono Olho Mágico', price: 1800.0 },
      { name: 'Cadeira Gamer Flutuante Nimbus', price: 2200.0 },
      { name: 'Fone de Ouvido Telepático MindLink', price: 500.0 },
      { name: 'Smartwatch Despertador de Choque', price: 700.0 },
      { name: 'Drone Pega Ladrão SkyGuard', price: 3500.0 },
      { name: 'Controle Universal de Namorado', price: 999.0 },
      { name: 'Geladeira que Faz Café AutoBrew', price: 4200.0 },
      { name: 'Ventilador Turbo Tufão 9000', price: 800.0 },
      { name: 'Batedeira DJ MixMaster 5000', price: 300.0 },
      { name: 'Lanterna Solar IluminaTudo', price: 120.0 },
      { name: 'Pen Drive de Outra Dimensão', price: 150.0 },
      { name: 'Óculos VR do Futuro VisioX', price: 2500.0 },
      { name: 'Projetor Portátil CinemaBolso', price: 1000.0 },
      { name: 'Microfone ASMR SussurroMax', price: 400.0 },
      { name: 'Câmera de Segurança FantasmaView', price: 1200.0 },
      { name: 'Roteador Wi-Fi Turbo 9000G', price: 500.0 },
      { name: 'Robô Faxineiro AutoCleanX', price: 3500.0 },
      { name: 'Almofada com Carregador Wireless NapCharge', price: 250.0 },
      { name: 'Espelho Inteligente Narciso 2.0', price: 600.0 },
      { name: 'Smart TV com Alexa Fofoqueira', price: 3000.0 },
      { name: 'Capinha de Celular Anti-Queda Milagre', price: 80.0 },
      { name: 'Carregador Solar de Emergência SolPower', price: 180.0 },
      { name: 'Aspirador de Pó Silencioso WhisperVac', price: 700.0 },
      { name: 'Forno Inteligente que Twitta Receitas', price: 2800.0 },
      { name: 'Notebook que não Trava ZenBook Pro', price: 4500.0 },
      { name: 'Guarda-Chuva com Wi-Fi RainNet', price: 200.0 },
      { name: 'Cafeteira Inteligente WakeUpBrew', price: 900.0 },
      { name: 'Chinelo com GPS NuncaSePerde', price: 150.0 },
      { name: 'Caixa de Som com Siri Cantora', price: 700.0 },
      { name: 'Tênis com Turbo Boost RunFast', price: 1200.0 },
      { name: 'Bicicleta com Piloto Automático', price: 5000.0 },
      { name: 'Banheira com Bluetooth RelaxTub', price: 3500.0 },
      { name: 'Cofre com Reconhecimento Facial SafeFace', price: 2500.0 },
      { name: 'Luminária de Humor MoodLight', price: 400.0 },
      { name: 'Relógio que Conta Piadas TimeJoker', price: 850.0 },
      { name: 'Toalha que Seca em 2 Segundos TurboDry', price: 180.0 },
      { name: 'Garrafa Térmica Infinita HotForever', price: 220.0 },
      { name: 'Pipoqueira com Estouro Sincronizado', price: 300.0 },
      { name: 'Scanner de Rosto para Gatos', price: 650.0 },
      { name: 'Colchão que se Arruma Sozinho SmartBed', price: 8000.0 },
      { name: 'Tapete com Sensor de Pegadas', price: 400.0 },
      { name: 'Óculos que Traduz Pensamentos MindRead', price: 5000.0 },
      { name: 'Jaqueta com Aquecimento Solar SunWarm', price: 1300.0 },
      { name: 'Caneca com Controle de Temperatura HeatMug', price: 350.0 },
      { name: 'Cortina com Controle de Luminosidade AutoShade', price: 1200.0 },
      { name: 'Sofá que te Abraça HugCouch', price: 5500.0 },
      { name: 'Chuveiro com Controle de Fluxo WaterWise', price: 900.0 },
      { name: 'Fogão com Controle por Voz CookEasy', price: 3200.0 },
      { name: 'Relógio que Avisa Hora de Dormir SleepyTime', price: 400.0 },
      { name: 'Smartphone com Bateria Infinita EternalPhone', price: 10000.0 },
      { name: 'Monitor que Evita Procrastinação FocusView', price: 2500.0 },
      { name: 'Carregador Turbo SuperUltraFast', price: 200.0 },
      { name: 'Vaso de Planta com Lembrete de Regar', price: 350.0 },
      { name: 'Chaveiro que Nunca se Perde KeyFinder', price: 150.0 },
      { name: 'Guarda-roupa que Escolhe Roupas por Você', price: 4500.0 },
      { name: 'Garrafa que Filtra Água Instantaneamente', price: 600.0 },
      { name: 'Relógio que Preve o Clima WeatherGuru', price: 1000.0 },
      { name: 'Smartwatch que Monitora Sonhos DreamWatch', price: 900.0 },
    ])
  }
}
